on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install semantic release
        run: npm install semantic-release @semantic-release/changelog @semantic-release/git rexreplace -g
      - name: Find version from semantic release
        run: echo "APP_VERSION=$(npx semantic-release --dryRun | grep -oP 'Published release \K.*? ')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cancel if no new version needed
        uses: andymckay/cancel-action@0.2
        if: ${{env.APP_VERSION == ''}}
      - name: Update version in pubspec.yaml
        run: 'rexreplace "^version: (.+)" "version: $(echo $APP_VERSION | sed "s/ *$//g")+$GITHUB_RUN_ID" pubspec.yaml'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - run: flutter pub get
      - run: flutter build apk --no-sound-null-safety
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: GogoApp.apk
          path: build/app/outputs/flutter-apk/apk-release.apk
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
