on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone custom chewie plugin
        uses: actions/checkout@v2
        with:
          repository: hugo4715/plugins
          path: 'plugins'
      - name: Create symlink to plugins repo
        run: ln -s $GITHUB_WORKSPACE/plugins ../plugins && ls -l ..
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk